controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_login_check:
  path: /api/login_check

me:
    path: /api/me
    controller: App\Controller\meController